# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: ea57e96f7c09c0d4d28beff2a8182462f6af39b9363b4d94a13aea004ce2acb1d9437cfc3c693e53e7c9460b64081a1e700d308781eaf7fdf479d12512483857

test:
  secret_key_base: b3dda9e8bcd450c2f37ca82dfa8bc3cc909c0c550b0127f48e4d9b616043da922663beeffd4bdbc3ccc6266787c5ee9605e3af451ea0dc3e8ef9a6ef0c12c50f

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
